# Generated by Django 5.1.4 on 2025-01-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_juan', '0002_alter_user_email_alter_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='phone',
        ),
    ]
